config/routes.rb
Rails.application.routes.draw do



  devise_for :members,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get "/pages/:page" => "pages#show"

  resources :members do
    resources :teetimes do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :groups do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :reservations do
      get :join
      get :joinrequest
    end
  end


  namespace :api do
    namespace :v1 do
      resources :teetimes
    end
  end





  root "pages#show", page: "home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teetime.rb
class Teetime < ApplicationRecord
  validates :date, presence: true
  validates :time, presence: true
  validates :starting_hole, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 18 }
  # validates :creator_id, presence: true
  # validates :formatted_date, presence: true
  # validates :formatted_time, presence: true

  # has_and_belongs_to_many :members
  has_many :timesheets
  has_many :members, through: :timesheets
end

app/controllers/api/v1/teetimes_controller.rb
class Api::V1::TeetimesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @teetimes = Teetime.all.order("date DESC")
    @signed_in = !current_member.nil?
    @teetimes.each do |teetime|
      teetime.formatted_date = teetime.date.strftime('%a, %B %e ')
      teetime.formatted_time = teetime.time.strftime('%l:%M %p')
    end

    render json: {teetimes: @teetimes, signedIn: @signed_in}
  end

  def show
    @teetime = Teetime.find(params[:id])
    @members = @teetime.members.all
    @current_user = current_user
    # @members.each { |member| @teetimes << review.user }
    render json: { teetimes: @teetimes, members: @members, currentUser: @current_user }
  end
end

app/controllers/teetimes_controller.rb
class TeetimesController < ApplicationController
  # before_action :authorize_member, except: [:index, :show]

  require 'forecast_io'


  def index
    @teetimes = Teetime.all
    @member_can_create = !current_member.nil?

    @teetimes.each do |teetime|
      teetime.formatted_date = teetime.date.strftime('%a, %B %e ')
      teetime.formatted_time = teetime.time.strftime('%l:%M %p')
    end
  end

  def destroy
    @teetime = Teetime.find(params[:id])
    @teetime.destroy
    redirect_to member_teetimes_path
    flash[:notice] = "Teetime was Deleted"
  end

  def edit
    @teetime = Teetime.find(params[:id])
    @member = @teetime.members.first

    unless can_change?(@teetime)
      raise ActionController::RoutingError.new("Not Found")
    end

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@teetime)
    end
  end

  def show
    @teetime = Teetime.find(params[:id])
    @members = @teetime.members
    @member = @teetime.members.first
    @teetime_requests = Teetimerequest.where(teetime_id: @teetime.id)

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@teetime)
    end

    @member_can_join = false
    unless current_member.nil?
      @member_can_join = can_join?(@teetime)
    end


    @date_part = @teetime.date.to_s
    @time_part = @teetime.time.strftime('%H:%M:%S')
    @date_time = "#{@date_part}T#{@time_part}"

    @latitude = 42.3756
    @longitude = -71.1695
    @weather_summary = ForecastIO.forecast(@latitude, @longitude, time: @date_time).currently.summary
    @weather_temperature = ForecastIO.forecast(@latitude, @longitude, time: @date_time).currently.temperature
  end

  # TODO: make it so a teetime you are in cannot be joined twice
  # TODO: make is so you can leave a teetime

  def join
    @teetime = Teetime.find(params[:teetime_id])

    Timesheet.create(teetime: @teetime, member: current_member)
    Teetimerequest.where(teetime_id: @teetime.id, member_id: @teetime.members.last.id).destroy_all

    if @teetime.members.all.length == 4
      @teetime.full = true;
    end

    if @teetime.save
      flash[:notice] = "You joined #{@teetime.creator}'s teetime."
      redirect_to member_teetimes_path
    end
  end

  def joinrequest
    @teetime = Teetime.find(params[:teetime_id])

    Teetimerequest.create(member_id: current_member.id, teetime_id: @teetime.id)

    flash[:notice] = "You requested to joined #{@teetime.members.first.first_name} #{@teetime.members.first.last_name}'s teetime."
    redirect_to member_teetimes_path
  end

  def create
    @teetime = Teetime.new(teetime_params)

    @member = Member.find(params[:member_id])



    if @teetime.save
      flash[:notice] = "Teetime reserved"
      Timesheet.create(member: current_member, teetime: @teetime)
      redirect_to member_teetimes_path
    else
      flash[:notice] = "Teetime was not created"
      render :new
    end
  end

  def update
    @teetime = Teetime.find(params[:id])

    unless can_change?(@teetime)
      raise ActionController::RoutingError.new("Not Found")
    end

    if @teetime.update(teetime_params)
      flash[:notice] = "You edited a teetime."
      redirect_to member_teetime_path(@teetime)
    else
      flash[:notice] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def new
    @member = Member.find(params[:member_id])
    @teetime = Teetime.new

    @latitude = 42.3756
    @longitude = -71.1695
    @weather_summary = ForecastIO.forecast(@latitude, @longitude).currently.summary
    @weather_temperature = ForecastIO.forecast(@latitude, @longitude).currently.temperature
  end

  # TODO: can't join teetime if 4 or more people already joined
  # TODO: fix can't join if set to unjoinable

  private

  def teetime_params
    params.require(:teetime).permit(:date, :time, :unjoinable, :full, :starting_hole, :creator, :formatted_date, :formatted_time, :creator_id)
  end

  def can_change?(teetime)
    # current_member == teetime.members.first || current_member.role == "admin"
    current_member.role == "admin" || current_member == teetime.members.first
  end

  def can_join?(teetime)
    !teetime.unjoinable && teetime.members.all.length < 4
  end

  def authorize_member
    # if !member_signed_in? || !current_member.admin?
    if !member_signed_in? || !current_member.role == "admin"
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  ForecastIO.configure do |configuration|
    configuration.api_key = '3005c7b585dcfef488065585a2bee2a3'
  end


end

app/views/teetimes/_form.html.erb
<%= form_for [@member, @teetime] do |f| %>
  <div>
    <%= f.label :date %>
    <%= f.number_field :date %>
  </div>
  <div>
    <%= f.label :time %>
    <%= f.text_area :time %>
  </div>
  <div>
    <%= f.label :starting_hole %>
    <%= f.text_area :starting_hole %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/teetimes/edit.html.erb
<div class="row">
    <div class="homepage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered">Edit Your Teetime</h1>
          </div>
      </div>
    </div>
</div>
<br>
<br>

<%= form_for([@member, @teetime]) do |f| %>

<div class="row">
  <div class="column text-center small-12 large-6 small-centered large-centered">
    <div>
      <%= f.date_field :date, :placeholder => "Date (103093)", autofocus: true %>
    </div>

    <div>
      <%= f.time_field :time, :placeholder => "Time (1200)", autofocus: true %>
    </div>

    <div>
      <%= f.number_field :starting_hole, :placeholder => "Starting Hole", autofocus: true %>
    </div>

    <div class="custom-button">
        <%= f.label :unjoinable do %>
        <%= f.check_box :unjoinable, :id => "custom-checkbox" %>
        Make Private
        <% end %>
    </div>

    <div class="actions">
      <%= f.submit "Edit", :class => 'custom-button' %>
    </div>
    <div class="custom-button">
      <%= link_to 'Delete Teetime', member_teetime_path(@member, @teetime), data: {:confirm => 'Are you sure?'}, :method => :delete %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>

app/views/teetimes/index.html.erb
<div class="row">
  <div class="showpage-title">
    <div class="small-12 large-6 small-centered large-centered columns">
        <div class="content-box-form-title">
          <h1 class="homepage-title small-12 large-6 small-centered large-centered"> The Timesheet</h1>
        </div>
    </div>
  </div>
</div>
<br>
<br>


<div id='TeetimeList'></div>

app/views/teetimes/new.html.erb
<div class="row">
    <div class="homepage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered">Reserve a Teetime</h1>
          </div>
      </div>
    </div>
</div>
</div>
<br>

<div class="animated fadeInUp">
  <div class="column text-center small-12 large-6 small-centered large-centered">
    <div class="teetimes-box">
      <p class = "teetime-show-subtitle"> On Course Weather: <%= @weather_summary %>, <%= @weather_temperature %>&deg;F </p><br>
    </div>
  </div>
</div>
<br>
<br>

<%= form_for([@member, @teetime]) do |f| %>

<div class="animated fadeInUp">


<div class="row">
  <div class="column text-center small-12 large-6 small-centered large-centered">
    <div>
      <%= f.date_field :date, :placeholder => "Date (103093)", autofocus: true %>
    </div>

    <div>
      <%= f.time_field :time, :placeholder => "Time (1200)", autofocus: true %>
    </div>

    <div>
      <%= f.number_field :starting_hole, :placeholder => "Starting Hole", autofocus: true %>
    </div>

    <div class="custom-button">
        <%= f.label :unjoinable do %>
        <%= f.check_box :unjoinable, :id => "custom-checkbox" %>
        Make Private
        <% end %>
    </div>

    <div>
      <%= f.hidden_field :creator, :value => "#{current_member.last_name}, #{current_member.first_name}" %>
    </div>

    <div>
      <%= f.hidden_field :creator_id, :value => current_member.id %>
    </div>



    <div class="actions">
      <%= f.submit "Reserve", :class => 'custom-button' %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>


</div>

app/views/teetimes/show.html.erb
<div class="row">
  <div class="showpage-title">
    <div class="small-12 large-6 small-centered large-centered columns">
        <div class="content-box-form-title">
          <% if @teetime.unjoinable %>
            <h1 class="homepage-title small-12 large-6 small-centered large-centered"> <%= @teetime.members.first.first_name %> <%= @teetime.members.first.last_name %>'s Private Teetime</h1>
          <% else %>
            <h1 class="homepage-title small-12 large-6 small-centered large-centered"> <%= @teetime.members.first.first_name %> <%= @teetime.members.first.last_name %>'s Teetime</h1>
          <% end %>
        </div>
    </div>
  </div>
</div>
<br>
<br>


<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "teetime-show-subtitle">Starting on hole <%= @teetime.starting_hole %>, at <%= @teetime.time.strftime('%l:%M %p ') %> on <%= @teetime.date.strftime('%a, %B %e ') %> </p>
  </div>
</div>

<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "teetime-show-subtitle"> Weather estimate: <%= @weather_summary %>, <%= @weather_temperature %>&deg;F </p><br>
  </div>
</div>
<br>

<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "custom-text-cursive">Player's List</p>
    <ul>
      <% @members.each do |member| %>
        <li class = "teetime-list">
          <%= member.last_name %>, <%= member.first_name %>
        </li>
      <% end %>
    </ul>
    <% if @teetime_requests.length != 0 %>
      <p class="custom-text-cursive">Requests</p>
      <ul>
        <% @teetime_requests.each do |request| %>
          <li class = "teetime-list">
            <% @request_member = Member.find(request.member_id) %>
            <%= @request_member.last_name %>, <%= @request_member.first_name %>
            <div class="custom-button-small-transparent">
              <%= link_to "Accept", member_teetime_join_path(teetime_id: @teetime.id) %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <br>


  <% unless current_member.nil? %>
    <% if @member_can_join %>
      <div class="custom-button">
        <%= link_to "Request Join", member_teetime_joinrequest_path(teetime_id: @teetime.id) %>
      </div>
    <% end %>
  <% end %>

  <% unless current_member.nil? %>
    <% if @member_can_change  %>
      <div class="custom-button">
        <%= link_to "Edit", edit_member_teetime_path %>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<br>