config/routes.rb
Rails.application.routes.draw do



  devise_for :members,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get "/pages/:page" => "pages#show"

  resources :members do
    resources :teetimes do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :groups do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :reservations do
      get :join
      get :joinrequest
    end
  end


  namespace :api do
    namespace :v1 do
      resources :teetimes
    end
  end





  root "pages#show", page: "home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, null: false

  has_many :memberships
  has_many :members, through: :memberships

  has_many :grouprequests
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :authorize_member, except: [:index, :show]

  def index
    @groups = Group.all
    @member_can_create = !current_member.nil?
    @view_all = true
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to member_groups_path
    flash[:notice] = "Group was Deleted"
  end

  def edit
    @group = Group.find(params[:id])
    @member = @group.members.first

    unless can_change?(@group)
      raise ActionController::RoutingError.new("Not Found")
    end

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@group)
    end
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.members
    @member = @group.members.first
    @group_requests = Grouprequest.where(group_id: @group.id)

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@group)
    end
  end

  # TODO: make it so a group you are in cannot be joined twice
  # TODO: make is so you can leave a group

  def join
    @group = Group.find(params[:group_id])

    Membership.create(group: @group, member: current_member)
    Grouprequest.where(group_id: @group.id, member_id: @group.members.last.id).destroy_all

    if @group.save
      flash[:notice] = "Join request granted."
      redirect_to member_groups_path
    end
  end

  def joinrequest
    @group = Group.find(params[:group_id])

    Grouprequest.create(member_id: current_member.id, group_id: @group.id)


    flash[:notice] = "You requested to joined #{@group.name}."
    redirect_to member_groups_path
  end


  def change_view
    @view_all = false
    redirect_to member_groups_path
  end

  def create
    @group = Group.new(group_params)

    @member = Member.find(params[:member_id])

    if @group.save
      flash[:notice] = "group reserved"
      Membership.create(member: current_member, group: @group)
      redirect_to member_groups_path
    else
      flash[:notice] = "group was not created"
      render :new
    end
  end

  def update
    @group = Group.find(params[:id])

    unless can_change?(@group)
      raise ActionController::RoutingError.new("Not Found")
    end

    if @group.update(group_params)
      flash[:notice] = "You edited a group."
      redirect_to member_group_path(@group)
    else
      flash[:notice] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def new
    @member = Member.find(params[:member_id])
    @group = Group.new
  end

  # TODO: can't join group if 4 or more people already joined
  # TODO: fix can't join if set to unjoinable

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def can_change?(group)
    # current_member == group.members.first || current_member.role == "admin"
    current_member.role == "admin" || current_member == group.members.first
  end

  def authorize_member
    # if !member_signed_in? || !current_member.admin?
    if !member_signed_in? || !current_member.role == "admin"
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/groups/index.html.erb
<div class="row">
  <div class="showpage-title">
    <div class="small-12 large-6 small-centered large-centered columns">
        <div class="content-box-form-title">
          <h1 class="homepage-title small-12 large-6 small-centered large-centered"> Your Groups</h1>
        </div>
    </div>
  </div>
</div>
<br>
<br>


  <div class="animated slideInLeft">
    <div class="text-center small-12 large-8 small-centered large-centered">
      <ul>
        <% @groups.each do |group| %>
          <% group.members.each do |member| %>
            <% if member.id == current_member.id %>
              <div class="teetimes-box">
                <li class = "teetime-list">
                  <a href="/members/<%= current_member.id %>/groups/<%= group.id %>">
                    <%= group.name %>
                  </a>
                </li>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>



  <div class="animated slideInRight">
  <div class="row">
      <div class="homepage-title">
        <div class="small-12 large-6 small-centered large-centered columns">
            <div class="content-box-form-title">
              <h1 class="homepage-title small-3 large-6 small-centered large-centered">All Groups</h1>
            </div>
        </div>
      </div>
  </div>
  </div>
  <br>
  <br>


  <div class="animated slideInLeft">
    <div class="text-center small-12 large-8 small-centered large-centered">
      <ul>
        <% @groups = Group.all %>
        <% @groups.each do |group| %>
              <div class="teetimes-box">
                <li class = "teetime-list">
                  <a href="/members/<%= current_member.id %>/groups/<%= group.id %>">
                    <%= group.name %>
                  </a>
                </li>
              </div>

        <% end %>

      </ul>
    </div>
  </div>

app/views/groups/new.html.erb
<div class="row">
    <div class="homepage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered">Create a Group</h1>
          </div>
      </div>
    </div>
</div>
<br>
<br>

<%= form_for([@member, @group]) do |f| %>

<div class="row">
  <div class="column text-center small-12 large-6 small-centered large-centered">

    <div>
      <%= f.text_field :name, :placeholder => "Name?", autofocus: true %>
    </div>


    <div class="actions">
      <%= f.submit "Create", :class => 'custom-button' %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="showpage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
        <div class="content-box-form-title">
          <h1 class="homepage-title small-3 large-6 small-centered large-centered"> <%= @group.name %> </h1>
        </div>
      </div>
    </div>

<br>

<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "custom-text-cursive">Members</p>
    <ul>
      <% @members.each do |member| %>
        <li class = "teetime-list">
          <%= member.last_name %>, <%= member.first_name %>
        </li>
      <% end %>
    </ul>
    <% if @group_requests.length != 0 %>
      <p class = "custom-text-cursive">Requests</p>
      <ul>
        <% @group_requests.each do |request| %>
          <li class = "teetime-list">
            <% @request_member = Member.find(request.member_id) %>
            <%= @request_member.last_name %>, <%= @request_member.first_name %>
            <div class="custom-button-small-transparent">
              <%= link_to "Accept", member_group_join_path(group_id: @group.id) %>
            </div>
          </li>
        <% end %>
      </ul>
      <% end %>

    <div class="custom-button-bottom-spacing">
      <%= link_to "Request Join", member_group_joinrequest_path(group_id: @group.id) %>
    </div>
  </div>
</div>

<br>

<row>
  <div class="column text-center small-12 large-6">
    <div class="teetimes-box">
      <h3 class = "custom-text-cursive">Teetimes</h3>
      <ul>
        <% @members.each do |member| %>
          <% unless member.teetimes.length == 0 %>
            <h4 class="member-heading">  <%= member.first_name %> <%= member.last_name %> </h4>
            <% member.teetimes.each do |teetime| %>
              <li class = "teetime-list">
                <a href="/members/<%= current_member.id %>/teetimes/<%= teetime.id %>"><%= teetime.date.strftime('%a, %B %e ')%> | <%= teetime.time.strftime('%l:%M %p') %> </a>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="column text-center small-12 large-6">
    <div class="teetimes-box">
      <h3 class = "custom-text-cursive">Reservations</h3>
      <ul>
        <% @members.each do |member| %>
          <% unless member.reservations.length == 0 %>
            <h4 class="member-heading">  <%= member.first_name %> <%= member.last_name %> </h4>
            <% member.reservations.each do |reservation| %>
              <li class = "teetime-list">
                <a href="/members/<%= current_member.id %>/reservations/<%= reservation.id %>"><%= reservation.date.strftime('%a, %B %e ')%> | <%= reservation.time.strftime('%l:%M %p') %> </a>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</row>
<br>
<br>
<br>