config/routes.rb
Rails.application.routes.draw do



  devise_for :members,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get "/pages/:page" => "pages#show"

  resources :members do
    resources :teetimes do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :groups do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :reservations do
      get :join
      get :joinrequest
    end
  end


  namespace :api do
    namespace :v1 do
      resources :teetimes
    end
  end





  root "pages#show", page: "home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :date, presence: true
  validates :time, presence: true
  validates :party_size, numericality: { greater_than: 0 }
  validates :room, presence: true
  # has_and_belongs_to_many :members
  has_many :dinings
  has_many :members, through: :dinings
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @member = Member.find(params[:member_id])

    if @reservation.save
      flash[:notice] = "Reservation reserved"
      Dining.create(member: current_member, reservation: @reservation)
      redirect_to member_reservations_path
    else
      flash[:notice] = "Reservation was not created"
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to member_reservations_path
    flash[:notice] = "Reservation was Deleted"
  end

  # TODO: add google calendar integration

  def join
    @reservation = Reservation.find(params[:reservation_id])
    Dining.create(reservation: @reservation, member: current_member)
    Reservationrequest.where(reservation_id: @reservation.id, member_id: @reservation.members.last.id).destroy_all
    flash[:notice] = "You joined #{@reservation.members.first.first_name} #{@reservation.members.first.last_name}'s reservation."
    redirect_to member_reservations_path
  end

  def joinrequest
    @reservation = Reservation.find(params[:reservation_id])

    Reservationrequest.create(member_id: current_member.id, reservation_id: @reservation.id)

    flash[:notice] = "You requested to joined #{@reservation.members.first.first_name} #{@reservation.members.first.last_name}'s reservation."
    redirect_to member_reservations_path
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @member = @reservation.members.first

    unless can_change?(@reservation)
      raise ActionController::RoutingError.new("Not Found")
    end

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@reservation)
    end
  end

  def new
    @member = Member.find(params[:member_id])
    @reservation = Reservation.new
  end

  def show
    @reservation = Reservation.find(params[:id])
    @members = @reservation.members
    @member = @reservation.members.first
    @reservation_requests = Reservationrequest.where(reservation_id: @reservation.id)

    @member_can_change = false
    unless current_member.nil?
      @member_can_change = can_change?(@reservation)
    end
  end

  private

  def can_change?(reservation)
    # current_member == teetime.members.first || current_member.role == "admin"
    current_member.role == "admin" || current_member == reservation.members.first
  end

  def authorize_member
    # if !member_signed_in? || !current_member.admin?
    if !member_signed_in? || !current_member.role == "admin"
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def reservation_params
    params.require(:reservation).permit(:date, :time, :party_size, :room)
  end
end

app/views/reservations/edit.html.erb
<div class="row">
    <div class="homepage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered">Edit Your Reservation</h1>
          </div>
      </div>
    </div>
</div>
<br>
<br>

<%= form_for([@member, @reservation]) do |f| %>

<div class="row">
  <div class="column text-center small-12 large-6 small-centered large-centered">

    <div>
      <%= f.select :room, [['Dining Room','dining room'],['Grille Room','grille room'],['Pub','pub']] %>
    </div>

    <div>
      <%= f.number_field :party_size, :placeholder => "party size", autofocus: true %>
    </div>

    <div>
      <%= f.date_field :date, :placeholder => "Date (103093)", autofocus: true %>
    </div>

    <div>
      <%= f.time_field :time, :placeholder => "Time (1200)", autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Save", :class => 'custom-button' %>
    </div>
    <div class="custom-button">
      <%= link_to 'Delete', member_reservation_path(@member, @reservation), data: {:confirm => 'Are you sure?'}, :method => :delete %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="row">
  <div class="showpage-title">
    <div class="small-12 large-6 small-centered large-centered columns">
        <div class="content-box-form-title">
          <h1 class="homepage-title small-12 large-6 small-centered large-centered"> Reservations</h1>
        </div>
    </div>
  </div>
</div>
<br>
<br>



<div class="animated slideInLeft">
  <div class="text-center small-12 large-8 small-centered large-centered">
    <ul>
      <% @reservations.each do |reservation| %>
        <div class="teetimes-box">
          <li class = "teetime-list">
            <a href="/members/<%= current_member.id %>/reservations/<%= reservation.id %>">
              <%= reservation.members.first.last_name %>, <%= reservation.members.first.first_name %>   |   <%= reservation.date.strftime('%a, %B %e ') %> at <%= reservation.time.strftime('%l:%M %p') %>   |   <%= reservation.room %>
            </a>
          </li>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="row">
    <div class="homepage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered">Make a Reservation</h1>
          </div>
      </div>
    </div>
</div>
<br>
<br>

<%= form_for([@member, @reservation]) do |f| %>

<div class="row">
  <div class="column text-center small-12 large-6 small-centered large-centered">

    <div>
      <%= f.select :room, [['Dining Room','dining room'],['Grille Room','grille room'],['Pub','pub']] %>
    </div>

    <div>
      <%= f.number_field :party_size, :placeholder => "party size", autofocus: true %>
    </div>

    <div>
      <%= f.date_field :date, :placeholder => "Date (103093)", autofocus: true %>
    </div>

    <div>
      <%= f.time_field :time, :placeholder => "Time (1200)", autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Reserve", :class => 'custom-button' %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="row">
    <div class="showpage-title">
      <div class="small-12 large-6 small-centered large-centered columns">
          <div class="content-box-form-title">
            <h1 class="homepage-title small-3 large-6 small-centered large-centered"> <%= @reservation.members.first.first_name %> <%= @reservation.members.first.last_name %>'s Reservation</h1>
          </div>
      </div>
    </div>
</div>
<br>

<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "teetime-show-subtitle">Dining in the <%= @reservation.room %>, at <%= @reservation.time.strftime('%l:%M %p ') %> on <%= @reservation.date.strftime('%a, %B %e ') %> </p>
  </div>
</div>
<br>

<div class="column text-center small-12 large-6 small-centered large-centered">
  <div class="teetimes-box">
    <p class = "custom-text-cursive">The Party of <%= @reservation.members.length %></p>
    <ul>
      <% @members.each do |member| %>
        <li class = "teetime-list">
          <%= member.last_name %>, <%= member.first_name %>
        </li>
      <% end %>
    </ul>
    <% if @reservation_requests.length != 0 %>
      <p class="custom-text-cursive">Requests</p>
      <ul>
        <% @reservation_requests.each do |request| %>
          <li class = "teetime-list">
            <% @request_member = Member.find(request.member_id) %>
            <%= @request_member.last_name %>, <%= @request_member.first_name %>
            <div class="custom-button-small-transparent">
              <%= link_to "Accept", member_reservation_join_path(reservation_id: @reservation.id) %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <br>
  <div class="custom-button">
    <%= link_to "Request", member_reservation_joinrequest_path(reservation_id: @reservation.id) %>
  </div>

  <% unless current_member.nil? %>
    <% if @member_can_change  %>
      <div class="custom-button">
        <%= link_to "Edit", edit_member_reservation_path %>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<br>