config/routes.rb
Rails.application.routes.draw do



  devise_for :members,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get "/pages/:page" => "pages#show"

  resources :members do
    resources :teetimes do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :groups do
      get :join
      get :joinrequest
    end
  end

  resources :members do
    resources :reservations do
      get :join
      get :joinrequest
    end
  end


  namespace :api do
    namespace :v1 do
      resources :teetimes
    end
  end





  root "pages#show", page: "home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <%= stylesheet_link_tag    "application" %>

    <%= csrf_meta_tags %>
    <!-- <link rel="stylesheet" href="animate.css">
    <script src="js/wow.min.js"></script>
    <script>new WOW().init();</script> -->
  </head>

  <body>
    <div class="animated fadeInDown">


      <div class="top-bar">
        <div class="top-bar-title">
          <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
            <button class="menu-icon dark" type="button" data-toggle></button>
          </span>
          <a href="/">Gopher</a>
        </div>
        <div id="responsive-menu">
          <% if member_signed_in? %>
          <div class="top-bar-left">
            <ul class="dropdown menu" data-dropdown-menu>
              <li>
                <a href="#">Create</a>
                <ul class="menu vertical">
                  <div class="please-work">
                  <li><a href="/members/<%= current_member.id %>/teetimes/new">Teetime</a></li>
                  <li><a href="/members/<%= current_member.id %>/reservations/new">Dining Reservation</a></li>
                  <li><a href="/members/<%= current_member.id %>/groups/new">Group</a></li>
                  </div>
                </ul>
              </li>
              <li><a href="/members/<%= current_member.id %>/teetimes">Teetimes</a></li>
              <li><a href="/members/<%= current_member.id %>/reservations">Reservations</a></li>
              <li><a href="/members/<%= current_member.id %>/groups">Groups</a></li>
            </ul>
          </div>
          <div class="top-bar-right">
            <ul class="menu">
              <li><%= link_to 'Sign Out', destroy_member_session_path, :method => :delete %></li>
              <li><a href='/members/edit'><%= current_member.last_name %>, <%= current_member.first_name %></a></li>
              <li>&nbsp;</li>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
  </div>



    <div class='animated fadeInDown error-msg'>
      <% flash.each do |name, msg| %>
        <div class='error-msg'>
          <% msg = "Invalid Electronic Mail or Password" if msg == 'Invalid Email or password.' %><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>

    <div class="content">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>



</html>

app/views/layouts/hold.html.erb
<div class="animated fadeInDown">
  <div class="top-bar">
    <div class="top-bar-title">
      <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
    <a href="/">Gopher</a>
  </div>
  <div class="responsive-menu">
    <% if member_signed_in? %>
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text"></li>
          <li>
            <a href= "#" >Schedule</a>
            <ul class="menu vertical">
              <li><a href="/members/<%= current_member.id %>/teetimes/new">Teetime</a></li>
              <li><a href="/members/<%= current_member.id %>/reservations/new">Dining</a></li>
              <li><a href="#">Three</a></li>
            </ul>
          </li>
      <li><a href="/members/<%= current_member.id %>/teetimes">Teetimes</a></li>
      <li><a href="/members/<%= current_member.id %>/reservations">Reservations</a></li>
    </ul>
  </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href='/members/sign_out'>Sign out?</a></li>
        <li><a href='/members/edit'><%= current_member.last_name %>, <%= current_member.first_name %></a></li>
      </ul>
    </div>
  <% end %>
</div>
</div>
</div>